spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:c2VjcmV0a2V5Zm9yc3RyaXBld2FsbGV0YXBpMTIzNDU2Nzg5MA==}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
